//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseInf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseInf()
        {
            this.Countries = new HashSet<Country>();
        }
    
        public int Id { get; set; }
        public string Languages { get; set; }
        public string FormOfGovern { get; set; }
        public string Religions { get; set; }
        public Nullable<double> Territory { get; set; }
        public Nullable<double> Population { get; set; }
        public string Currency { get; set; }
        public string ImgFlag_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }
    }
}
