//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Showplaces = new HashSet<Showplace>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Capital { get; set; }
        public string ShortDescription { get; set; }
        public byte[] Img { get; set; }
        public string Location { get; set; }
        public string BaseFacts { get; set; }
        public string Cities { get; set; }
        public int BaseInf_Id { get; set; }
        public string Img_path { get; set; }
    
        public virtual BaseInf BaseInf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Showplace> Showplaces { get; set; }
    }
}
