//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities() : base("name=DatabaseEntities")
        {
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<BaseInf> BaseInfs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Showplace> Showplaces { get; set; }
        public virtual DbSet<TestType> TestTypes { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    }
}
